services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn-gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    dns: 1.1.1.1
    ports:
      - "8000:8000" # gluetun HTTP control server
      - "6081:6081" # nicotine web UI (https) (main)
      - "6080:6080" # nicotine web UI (http)
      - "1080:1080" # socks proxy (see below)
      - 2234-2239:2234-2239 # ?
      - "8080:8080" # qbittorrent webui
    volumes:
      - /var/lib/nicotine-vpn/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=${WG_ADDRESSES}
      - WIREGUARD_ENDPOINT_IP=${WG_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WG_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WG_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      # define control API
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"basic","username":"${GLUETUN_USER}","password":"${GLUETUN_PASS}"}
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  socks-proxy:
    image: tarampampam/3proxy
    container_name: socks-proxy
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    restart: unless-stopped

  nicotine:
    build: .
    container_name: nicotine-plus
    network_mode: "service:vpn"  # share namespace, ports on vpn service
    depends_on:
      vpn:
        condition: service_healthy
    security_opt:
      - seccomp:unconfined  # required for GUI app to function correctly in container
    environment:
      - PUID=1000
      - PGID=100  # match `$ id <username>`
      - TZ=America/New_York
      - LISTENING_PORT=  # unset default of 2234
      - GLUETUN_USER=${GLUETUN_USER}  # used by nicotine+ auto-set port plugin
      - GLUETUN_PASS=${GLUETUN_PASS}  # used by nicotine+ auto-set port plugin
      # - PASSWORD=${NICOTINE_WEB_PASSWORD}    # web UI login
      # - CUSTOM_USER=${NICOTINE_WEB_USERNAME} # web UI login
    volumes:
      - /var/lib/nicotine-vpn/config:/config  # persists nicotine config, credentials, and plugins
      - /mnt/audio/shared:/shared:ro
      - /mnt/audio/downloads:/data/downloads:rw
      - /mnt/audio/incomplete_downloads:/data/incomplete_downloads:rw
    shm_size: "1gb"  # for web UI streaming stability
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /var/lib/qbittorrent-vpn/config:/config
      - /home/rin/Torrents/downloads:/downloads
    restart: unless-stopped

  qbittorrent-port-sync:
    image: mjmeli/qbittorrent-port-forward-gluetun-server
    container_name: qbittorrent-port-sync
    restart: unless-stopped
    depends_on:
      vpn:
        condition: service_healthy
    environment:
      - QBT_USERNAME=admin
      - QBT_PASSWORD=${QBT_WEBUI_PASSWORD}
      - QBT_ADDR=http://vpn:8080
      - GTN_ADDR=http://vpn:8000
      - GTN_USERNAME=${GLUETUN_USER}
      - GTN_PASSWORD=${GLUETUN_PASS}

    # TODO! add more things here
