networks:
  playit-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/29

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    restart: unless-stopped
    networks:
      playit-net:
        ipv4_address: 172.28.0.2
    environment:
      SECRET_KEY: "${PLAYIT_SECRET_KEY}"
    # secrets:
    #   - playit-secret.key
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
    # user: "4440:4440"

  mc:
    image: itzg/minecraft-server:stable
    container_name: minecraft
    tty: true
    stdin_open: true
    user: "4440:4440"
    networks:
      playit-net:
        ipv4_address: 172.28.0.3
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "6144M" # 75% of mem_limit
      USE_MEOWICE_FLAGS: "true"
      ONLINE_MODE: "TRUE"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      ENABLE_RCON: "true"
      RCON_PORT: "25575"
      RCON_PASSWORD_FILE: "/run/secrets/mc-rcon-pass.key"
    volumes:
      - ./data:/data
      # - /etc/secrets/mc-rcon-pass.key:/run/secrets/mc-rcon-pass.key:ro
    secrets:
      - mc-rcon-pass.key
    tmpfs:
      - /tmp:exec,mode=1777,size=1g
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    read_only: true  # remove if plugins cause perm denied errors
    mem_limit: 8g
    cpus: 3.5
    pids_limit: 512
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  backups:
    image: itzg/mc-backup:stable
    container_name: minecraft-backup
    networks:
      playit-net:
        ipv4_address: 172.28.0.4
    environment:
      RCON_HOST: "172.28.0.3"
      RCON_PASSWORD_FILE: "/run/secrets/mc-rcon-pass.key"
      BACKUP_INTERVAL: "6h"
      PRUNE_BACKUPS_DAYS: "7"
    secrets:
      - mc-rcon-pass.key
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      # - /etc/secrets/mc-rcon-pass.key:/run/secrets/mc-rcon-pass.key:ro
    depends_on:
      mc:
        condition: service_healthy
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
    user: "4440:4440"
    restart: unless-stopped

secrets:
  # playit-secret.key:
  #   file: /etc/secrets/playit-secret.key
  mc-rcon-pass.key:
    file: /etc/secrets/mc-rcon-pass.key
